DROP INDEX "balance_audit_createdAt_idx";--> statement-breakpoint
DROP INDEX "cash_movement_responsibleId_idx";--> statement-breakpoint
DROP INDEX "cash_movement_type_idx";--> statement-breakpoint
DROP INDEX "credit_note_invoiceId_idx";--> statement-breakpoint
DROP INDEX "customer_phone_idx";--> statement-breakpoint
DROP INDEX "inventory_count_operative_status_idx";--> statement-breakpoint
DROP INDEX "invoice_issuedAt_idx";--> statement-breakpoint
DROP INDEX "invoice_status_idx";--> statement-breakpoint
DROP INDEX "payment_method_isActive_idx";--> statement-breakpoint
DROP INDEX "payment_method_sortOrder_idx";--> statement-breakpoint
DROP INDEX "price_list_isActive_idx";--> statement-breakpoint
DROP INDEX "price_list_isPublic_idx";--> statement-breakpoint
DROP INDEX "product_imageUrl_idx";--> statement-breakpoint
DROP INDEX "product_lastMovementAt_idx";--> statement-breakpoint
DROP INDEX "purchase_voucher_status_idx";--> statement-breakpoint
DROP INDEX "purchase_voucher_item_voucherId_idx";--> statement-breakpoint
DROP INDEX "role_permission_role_idx";--> statement-breakpoint
DROP INDEX "service_isActive_idx";--> statement-breakpoint
DROP INDEX "stock_movement_type_idx";--> statement-breakpoint
DROP INDEX "supplier_isActive_idx";--> statement-breakpoint
DROP INDEX "user_role_role_idx";--> statement-breakpoint
DROP INDEX "vehicle_category_idx";--> statement-breakpoint
DROP INDEX "vehicle_identifier_idx";--> statement-breakpoint
DROP INDEX "work_order_scheduledDate_idx";--> statement-breakpoint
DROP INDEX "work_order_audit_log_changedAt_idx";--> statement-breakpoint
DROP INDEX "work_order_audit_log_changedBy_idx";--> statement-breakpoint
DROP INDEX "work_order_audit_log_fieldName_idx";